import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import Navbar from './components/Navbar';
import './globals.css';

import AuthProvider from '@/provider/AuthProvider';
import { getUserInfo } from '@/utils/getUserInfo';
import { ToastContainer } from 'react-toastify';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  let userInfo = await getUserInfo();

  return (
    <html lang="en">
      <AuthProvider userInfo={userInfo}>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
          suppressHydrationWarning
        >
          <header>
            <Navbar />
          </header>
          {children}
          <ToastContainer />
        </body>
      </AuthProvider>
    </html>
  );
}
